var languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
var firstElement = languages[0];
var thirdElement = languages[2];
var length = languages.length;
var lastElement = languages[length - 1];
console.log(languages);
console.log('the first element of the array is ' + firstElement);
console.log('the third element of the awway is ' + thirdElement);
console.log('the length of the array is ' + length);
console.log('the last element of the array is ' + lastElement);
